spring:
  application:
    name: order-service
  rabbitmq: 
    host: 192.168.64.5
    port: 5672
    username: admin
    password: admin
#server:#  port: 8201
# eureka 微服务端配置
eureka:  client:    service-url:
      defaultZone: http://127.0.0.1:2001/eureka,http://127.0.0.1:2002/eureka
# 启用 hystrix 配置   feign: 
  hystrix:    enabled: true
    
   
# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
---
spring:  profiles: order-8201
server:  port: 8201
  
  

---
spring:  profiles: order-8202
server:  port: 8202
  