
sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"}]"


spring:
  application:
    name: user-service
    
server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka
